- name: "Check if migration {{ migration_name }} has a critical condition"
  k8s_facts:
    kind: MigPlan
    api_version: v1alpha1
    namespace: "{{ migration_namespace }}"
    name: "{{ migration_plan_name }}"
  register: mig_plan
  until:  mig_plan.resources[0].status.get('conditions', {}) | list | selectattr( "type", "equalto", "NamespaceLimitExceeded") | selectattr( "category", "equalto", "Critical") | list | length > 0
  retries: 30

- name: "Max-namespaces critical condition found"
  debug: 
    msg: "{{ mig_plan.resources[0].status.get('conditions', {}) | list | selectattr( 'type', 'equalto', 'NamespaceLimitExceeded') | selectattr( 'category', 'equalto', 'Critical') | list }}"

- name: Remove the blocked execution
  k8s:
    api_version: migration.openshift.io/v1alpha1
    state: absent
    kind: MigMigration
    name: "{{ migration_name }}"
    namespace: "{{ migration_namespace }}"

- name: Restore mig controller initial limit values
  k8s:
    api_version: migration.openshift.io/v1alpha1
    namespace: "{{ migration_namespace }}"
    definition: "{{ previous_controller }}"
