- name: Check resources status
  k8s_facts:
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors: "run={{ item }}"
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 30
  delay: 15
  with_items:
   - "test-dc"
   - "test-job"
   - "test-standalone"
   - "test-deployment"
   - "test-statefulset"
   - "test-daemonset"
