- name: Get mig controller information
  k8s_facts:
    api_version: migration.openshift.io/v1alpha1
    kind: MigrationController
    name: migration-controller
    namespace: "{{ migration_namespace }}"
  register: mig_controller
  until: mig_controller.resources | length > 0

- name: Store controller config, removing the resource version
  set_fact:
    previous_controller: >-
                         {{ (mig_controller.resources|first)|
                          combine({'metadata':{
                                                'name': (mig_controller.resources|first).metadata.name,
                                                'namespace': (mig_controller.resources|first).metadata.namespace } }) }}

- name: Update mig controller with the new pod limit
  k8s:
    api_version: migration.openshift.io/v1alpha1
    namespace: "{{ migration_namespace }}"
    definition: "{{ previous_controller | combine({ 'spec': {'mig_pod_limit': pod_limit|string } }) }}"


- name: Execute migration
  include_role:
    name: migration_run
  vars:
    wait_for_warnings: true
