- hosts: localhost
  roles:
    - { role: migration_prepare, tags: ["always"] }
    - { role: mssql-app, tags: ["mssql-app"], pv_action: 'copy', pv_copy_method: 'snapshot', stage: 'true', src_storage_class: 'gp2', dst_storage_class: 'gp2' }
    - { role: sock-shop, tags: ["sock-shop"], pv_action: 'copy', pv_copy_method: 'snapshot', src_storage_class: 'gp2', dst_storage_class: 'gp2' }
    - { role: parks-app, tags: ["parks-app"], pv_action: 'copy', pv_copy_method: 'snapshot', src_storage_class: 'gp2', dst_storage_class: 'gp2' }
    - { role: robot-shop, tags: ["robot-shop"], pv_action: 'copy', pv_copy_method: 'snapshot', stage: 'true', src_storage_class: 'gp2', dst_storage_class: 'gp2' }
  vars_files:
    - "{{ playbook_dir }}/config/mig_controller.yml"
    - "{{ playbook_dir }}/config/defaults.yml"
