namespace: ocp-25212-initcont
replicas: 1

int_app_name: internal-nginx
ext_app_name: external-nginx

external_image_name: docker.io/alpine
internal_image_name: internal-alpine
internal_image_tag: int

migration_sample_name: ocp-25212-initcont
migration_plan_name: "{{ migration_sample_name }}-migplan-{{ ansible_date_time.epoch }}"
migration_name: "{{ migration_sample_name }}-mig-{{ ansible_date_time.epoch }}"
#migration_sample_files: "{{ playbook_dir }}/mig-controller/docs/scenarios/{{ migration_sample_name }}"
with_deploy: true
with_migrate: true
with_cleanup: true
with_validate: true
pv: false
quiesce: false
