- name: Check mysql status
  k8s_facts:
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors: "app=mysql"
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 30
  delay: 10

- name: Check if volume is bound
  k8s_facts:
    kind: PersistentVolumeClaim
    namespace: "{{ namespace }}"
    label_selectors: "app=mysql"
  register: volume
  until: volume.get("resources", []) and volume.resources[0].get("status", {}).get("phase", "") == "Bound"
  retries: 10
  delay: 15
