# Fix for OCP3.7-9
# See : https://github.com/fusor/mig-demo-apps/issues/7
- name: Create namespace for {{ migration_sample_name }}
  shell: "{{ oc_binary }} new-project {{ namespace }} --skip-config-write=true"

- name: Deploy {{ migration_sample_name }} sample
  k8s:
    state : present
    definition: "{{ lookup('template', 'manifest.yml' )}}"
    wait: yes

- name: Check s2i build {{ migration_sample_name }} restify is completed
  k8s_facts:
    kind: Build
    api_version: build.openshift.io/v1
    namespace: "{{ namespace }}"
    label_selectors: "app=restify"
  register: s2i
  until: s2i.resources | length > 0 and s2i.resources[0].get("status", {}).get("phase", "") == "Complete"
  retries: 30
  delay: 10
