- name: Check Role
  k8s_facts:
    api_version: "{{ role_api }}"
    kind: Role
    namespace: "{{ namespace }}"
    name: "{{ rolename }}"
  register: ret_role
  until: ret_role.resources | length > 0
  retries: 30

- name: Check RoleBinding
  k8s_facts:
    api_version: "{{ rolebinding_api }}"
    kind: RoleBinding
    name: "{{ rolebinding_name }}"
    namespace: "{{ namespace }}"
  register: role_binding
  until: role_binding.resources | length > 0
  retries: 30
