apis:
  cronjob:
    default: "batch/v1beta1"
    "3.7": "batch/v2alpha1"
  role:
    default: "rbac.authorization.k8s.io/v1beta1"
    "3.7": "v1"
  rolebinding:
    default: "rbac.authorization.k8s.io/v1beta1"
    "3.7": "v1"
