- name: Check external image nodes status
  k8s_facts:
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors: "app={{ ext_app_name}}"
  register: pod
  until: pod | json_query('resources[*].status.containerStatuses[*].ready') | flatten |difference( [true] ) | length  == 0
  delay: 10
  retries: 30

- name: Check internal image nodes status
  k8s_facts:
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors: "app={{ int_app_name }}"
  register: pod
  until: pod | json_query('resources[*].status.containerStatuses[*].ready') | flatten |difference( [true] ) | length  == 0
  delay: 10
  retries: 30

- name: Obtain internal route
  k8s_facts:
    kind: Route
    namespace: "{{ namespace }}"
    label_selectors: "app={{ int_app_name }}"
  register: int_route
  delay: 10
  retries: 12
  until: int_route.resources | length > 0

- name: Obtain external route
  k8s_facts:
    kind: Route
    namespace: "{{ namespace }}"
    label_selectors: "app={{ ext_app_name}}"
  register: ext_route
  delay: 10
  retries: 12
  until: ext_route.resources | length > 0

- name: Access the internal route content
  uri:
    url: http://{{ int_route.resources[0].spec.host }}
    method: GET
    return_content: yes
  register: this
  delay: 10
  retries: 12
  until: "'<h1>HELLO WORLD</h1>' in this.content"

- name: Access the external route content
  uri:
    url: http://{{ ext_route.resources[0].spec.host }}
    method: GET
    return_content: yes
  register: this
  delay: 10
  retries: 12
  until: "'<h1>HELLO WORLD</h1>' in this.content"
